### ISSUE TITLE
Stegosaurus Polaroid Positionning

### ISSUE THREAD

**Issue by paiementstephanie** [acgd-webdev-3/interactive-polaroids#41]
@thomasjbradley 

Hello Thomas,

I can't seem to find a way to make the Stegosaurus Polaroid go behind the Pteranodon one.  I tried overflow:hidden and other positioning percentages but I can't seem to get it underneath.  I'm not really sure how to proceed.
<img width="524" alt="screen shot 2016-01-25 at 8 02 07 pm" src="https://cloud.githubusercontent.com/assets/10467614/12569892/0581a7a8-c3a1-11e5-814f-f2456d503e09.png">

**Comment by thomasjbradley** [comment]
Have you tried `z-index`?

**Comment by paiementstephanie** [comment]
yeah I do have them on all 3, the pteranodon is 3, step is 2 and the last one is 1

**Comment by paiementstephanie** [comment]
steg*

**Comment by paiementstephanie** [comment]
I thought the higher the number, the closer that element is on top

**Comment by paiementstephanie** [comment]
Oh, i had it on the wrong tags, Thank you!
